apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: saasportfolioreg.azurecr.io/backend:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 5205
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5205"
            - name: DP_KEYS_DIR
              value: "/app/dpkeys"
          volumeMounts:
            - name: dpkeys
              mountPath: /app/dpkeys
          readinessProbe:
            httpGet: { path: /API/health, port: 5205 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /API/health, port: 5205 }
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
      volumes:
        - name: dpkeys
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: { app: backend }
  ports:
    - name: http
      port: 5205
      targetPort: 5205
  type: ClusterIP
