apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: saasportfolioreg.azurecr.io/frontend:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DOTNET_API_BASE_URL
              value: "https://backend:5205/API"
            - name: NEXT_PUBLIC_SELF_URL
              value: "https://devoptics.mark-wolf.com"
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector: { app: frontend }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
