# k8s/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`devoptics.mark-wolf.com`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: backend
          port: 5205
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
