name: Build & Deploy - CLIENT -> ACA

name: Build & Deploy - Frontend

on:
  push:
    branches: [ghfrontend]

jobs:
  build-client:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ───── Azure / ACR login ─────
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: |
          docker login ${{ secrets.ACR_NAME }} \
            -u ${{ secrets.ACR_USERNAME }} \
            -p ${{ secrets.ACR_PASSWORD }}

      # ───── Build & push client image ─────
      - name: Build + push client
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker build \
            --build-arg NEXT_PUBLIC_SELF_URL="${{ secrets.NEXT_PUBLIC_SELF_URL }}" \
            --build-arg DOTNET_API_BASE_URL="${{ secrets.DOTNET_API_BASE_URL }}" \
            -t ${{ secrets.ACR_NAME }}/${{ secrets.CLIENT_IMAGE_REPO }}:${SHORT_SHA} \
            -f client/Dockerfile ./client
          docker push ${{ secrets.ACR_NAME }}/${{ secrets.CLIENT_IMAGE_REPO }}:${SHORT_SHA}
          docker tag  ${{ secrets.ACR_NAME }}/${{ secrets.CLIENT_IMAGE_REPO }}:${SHORT_SHA} \
                      ${{ secrets.ACR_NAME }}/${{ secrets.CLIENT_IMAGE_REPO }}:latest
          docker push ${{ secrets.ACR_NAME }}/${{ secrets.CLIENT_IMAGE_REPO }}:latest
          echo "SHA=$SHORT_SHA" >> $GITHUB_ENV

      # ───── Deploy container app ─────
      - name: Deploy client ACA
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.ACA_RESOURCE_GROUP }}
          containerAppName: ${{ secrets.CLIENT_ACA_NAME }}
          imageToDeploy: ${{ secrets.ACR_NAME }}/${{ secrets.CLIENT_IMAGE_REPO }}:${{ env.SHA }}
